build:
  dependencies:
    override:
    - echo "nothing is needed"

  environment:
    go: go1.9

  nodes:
    analysis:
      tests:
        override:
        - go-scrutinizer-run
        - govet-run
        - golint-run

  tests:
    override:
    #- command: make test-with-coverage-profile ARGS='-timeout=1s'
    #  coverage: { file: 'cover.out', format: 'go-cc' }
    - command: go test -race -coverprofile=cover-tmp.out github.com/kamilsk/check/http/availability
      coverage:
        file: 'cover-tmp.out'
        format: 'go-cc'

checks:
  go: true

filter:
  excluded_paths:
  - '/vendor/'
  - '*_test.go'
