build:
  dependencies:
    override:
    - echo "nothing is needed"

  environment:
    go: go1.9

    postgresql: false
    redis:      false

  tests:
    override:
    - go-scrutinizer-run
    - govet-run
    - golint-run
    - command: make test-with-coverage-profile ARGS='-timeout=1s'
      coverage: { file: cover.out, format: go-cc }

checks:
  go: true

filter:
  excluded_paths:
  - 'vendor/'
  - '*_test.go'
