build:
  dependencies:
    override:
    - echo "nothing is needed"

  environment:
    go: go1.9

  nodes:
    analysis:
      tests:
        override:
        - go-scrutinizer-run
        - govet-run
        - golint-run

  tests:
    override:
    - command: make test-with-coverage-profile ARGS='-timeout=1s'
      coverage: { file: cover.out, format: count }

checks:
  go: true

filter:
  excluded_paths:
  - 'vendor/'
  - '*_test.go'
