[[constraint]]
  name = "github.com/fatih/color"
  version = "^1.6.0"

[[constraint]]
  name = "github.com/gocolly/colly"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "*"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "*"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.2.0"

[prune]
  go-tests = true
  unused-packages = true
